apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8snet-deployment
  annotations:
    kubernetes.io/change-cause: "Initial deployment"

spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8snet
  template:
    metadata:
      name: k8snet-container
      labels:
        env: prod
        app: k8snet
        app.kubernetes.io/name: k8snet
    spec:
      containers:
      - name: k8snet
        image: god0nlyknows/k8s:latest
        ports:
        - containerPort: 80
          name: http-web-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80
---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    app: k8snet #ref name to app.kubernetes.io/name
  ports:
  - port: 8080
    targetPort: 80
    name: k8snet-port
    protocol: TCP
  type: LoadBalancer
